export const CONTENT_ROLES = [
  'SUPER_ADMIN',
  'ADMIN',
  'MANAGER_TEAM',
  'ASISTANT_TEAM',
  'MANAGER_NATIONAL_TEAM',
  'ASISTANT_NATIONAL_TEAM',
  'MANAGER_REGIONAL_TEAM',
  'ASISTANT_REGIONAL_TEAM',
  'MANAGER_LEAGUE',
  'ASISTANT_LEAGUE',
] as const;
